BEGIN;

ALTER TABLE salary_history 
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'Pending',
ADD COLUMN IF NOT EXISTS allowances JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS deductions JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS overtime_hours DECIMAL(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS overtime_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_days DECIMAL(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_day_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(50),
ADD COLUMN IF NOT EXISTS payment_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS paid_by INTEGER;

COMMIT;
